stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - src/deepClassifier/components/data_ingestion.py
      - src/deepClassifier/config/configuration.py
      - src/deepClassifier/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
