stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps: 
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - src/deepClassifier/components/data_ingestion.py
      - src/deepClassifier/config/configuration.py
      - src/deepClassifier/entity/config_entity.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip

  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps: 
      - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
      - src/deepClassifier/components/prepare_base_model.py
      - src/deepClassifier/config/configuration.py
      - src/deepClassifier/entity/config_entity.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps: 
      - src/deepClassifier/pipeline/stage_03_training.py
      - src/deepClassifier/config/configuration.py
      - src/deepClassifier/entity/config_entity.py
      - src/deepClassifier/components/training.py
      - src/deepClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/data.zip
    params:
      - AUGMENTATION
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
    outs:
      - artifacts/training/model.h5
      - artifacts/prepare_callbacks/checkpoint_dir/model.h5
      - artifacts/prepare_callbacks/tensorboard_log_dir